substitutions:
  _DEMO_REPO_NAME: run-cloud
  _DEMO_REGION: australia-southeast1
  _DEMO_COMPOSER_BUCKET: gs://vaulted-cogency-429801-h7_cloudbuild
steps:
  # Step 0: Clone the GitHub repository
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/Michellehlcn/${_DEMO_REPO_NAME}
      - ${_DEMO_REPO_NAME}

  # Step 1: Navigate to the app directory and build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_DEMO_REGION}-docker.pkg.dev/$PROJECT_ID/run-cloud/demo-app
      - -f
      - docker/Dockerfile
      - .
    dir: ${_DEMO_REPO_NAME}

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_DEMO_REGION}-docker.pkg.dev/$PROJECT_ID/run-cloud/demo-app

  # Step 3: Initialize Terraform
  - name: hashicorp/terraform:light
    entrypoint: terraform
    args:
      - init
    dir: ${_DEMO_REPO_NAME}/infra/sandbox

  # Step 4: Apply Terraform configuration
  - name: hashicorp/terraform:light
    entrypoint: terraform
    args:
      - apply
      - -auto-approve
    dir: ${_DEMO_REPO_NAME}/infra/sandbox

  # Step 5: Copy the DAGs folder
  - name: gcr.io/cloud-builders/gcloud
    args:
      - storage
      - cp
      - -r
      - ${_DEMO_REPO_NAME}/airflow/dags
      - ${_DEMO_COMPOSER_BUCKET}

  # Step 6: Deploy GCP Workflows configuration
  - name: gcr.io/cloud-builders/gcloud
    args:
      - workflows
      - deploy
      - cloud-run-job-workflow
      - --source=${_DEMO_REPO_NAME}/workflows/cloud-run-job-workflow.yaml
      - --location=${_DEMO_REGION}
      - --project=$PROJECT_ID
